KKRTheater/Development/KKRTheater/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KKRTheater.ViewModels;
using KKRTheater.ViewModels.Actors;
using TheaterData;
using TheaterData.Entities;
using Microsoft.Extensions.Logging;

namespace KKRTheater.Controllers
{
    public class ActorsController : Controller
    {
        private IActor _actors;
        private ILogger<ActorsController> _logger;
        private IMovie _movies;

        public ActorsController(IActor actors, IMovie movies, ILogger<ActorsController> logger)
        {
            _actors = actors;
            _movies = movies;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<Actor> actorModel = await _actors.GetAll();

            var listingResults = actorModel
                .Select(result => new ActorIndexListingModel
                {
                    Id = result.Id,
                    Name = result.Name
                });

            var model = new ActorIndexModel()
            {
                Actors = listingResults
            };

            return View(model);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Actor actor = await _actors.GetById(id);

            if (actor != null)
            {
                List<Movie> movies = await _actors.GetMovies(id);
                var detailModel = new ActorDetailModel
                {
                    Id = actor.Id,
                    Name = actor.Name,
                    Birthday = actor.Birthday.Equals(DateTime.MinValue) ? "" : actor.Birthday.ToString("MMMM dd yyyy"),
                    Birthplace = actor.Birthplace,
                    Bio = actor.Bio,
                    Movies = movies
                        .Select(movie => new KeyValuePair<int, string>(movie.Id, movie.Title))
                        .ToDictionary(kvp => kvp.Key, kvp => kvp.Value)
                };
                return View(detailModel);
            }

            return NotFound();
            
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([Bind("Name,Birthday,Birthplace,Bio")]Actor actor)
        {
            if (ModelState.IsValid)
            {
                Actor foundActor = await _actors.GetByName(actor.Name);

                if (foundActor == null)
                {
                    _actors.Add(actor);
                    ModelState.Clear();
                    ViewBag.UserMessage = "Actor Added";
                    return RedirectToAction($"Detail/{actor.Id}");
                }
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, string movieTitle = "")
        {
            //Avoid Null Exception when no search filter passed.
            if (movieTitle == null)
                movieTitle = "";

            Actor foundActor = await _actors.GetById(id);

            if (foundActor != null)
            {
                ActorEditModel viewModel = new ActorEditModel();
                viewModel.Name = foundActor.Name;
                viewModel.Id = foundActor.Id;

                ICollection<Movie> linkedMovies = foundActor.FilmCasts.Select(filmCast => filmCast.Movie).ToList();
                ICollection<Movie> allMovies = await _movies.GetAllLight();

                List<AssignedMovies> assignedMovies = allMovies.OrderBy(movie => movie.Title).Where(movie => movie.Title.Contains(movieTitle))
                    .Select(movie => new AssignedMovies
                    {
                        Id = movie.Id,
                        Title = movie.Title,
                        Assigned = linkedMovies.Contains(movie)
                    }).ToList();


                viewModel.AssignedMovies = assignedMovies;

                return View(viewModel);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ActorEditModel actorEditModel)
        {
            if (ModelState.IsValid)
            {
                Actor foundActor = await _actors.GetById(actorEditModel.Id);

                if (foundActor != null)
                {
                    foundActor.Name = actorEditModel.Name;

                    foreach (AssignedMovies assignedMovie in actorEditModel.AssignedMovies)
                    {
                        if (assignedMovie.Assigned)
                            _actors.AddMovie(foundActor, assignedMovie.Id);

                        else if (foundActor.FilmCasts.Select(filmCast => filmCast.MovieId).ToList().Contains(assignedMovie.Id))
                            _actors.RemoveMovie(foundActor, assignedMovie.Id);

                    }
                    _actors.Save();
                    ModelState.Clear();
                    return RedirectToAction($"Detail/{foundActor.Id}");
                }
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Actor foundActor = await _actors.GetById(id);
            if (foundActor != null)
            {
                ActorDeleteModel viewModel = new ActorDeleteModel();
                viewModel.Id = foundActor.Id;
                viewModel.Name = foundActor.Name;

                return View(viewModel);
            }

            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Actor foundActor = await _actors.GetById(id);

            if (foundActor != null)
            {
                _actors.Delete(foundActor);
            }
            return RedirectToAction("Index");
        }
    }
}

KKRTheater/Development/KKRTheater/Controllers/GenresController.cs
using KKRTheater.ViewModels.Genres;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TheaterData;
using TheaterData.Entities;

namespace KKRTheater.Controllers
{
    public class GenresController : Controller
    {
        private IGenre _genres;

        public GenresController(IGenre genres)
        {
            _genres = genres;
        }

        public async Task<IActionResult> Index()
        {
            ICollection<Genre> genreModel = await _genres.GetAll();

            var listingResults = genreModel
                .Select(result => new GenreIndexListingModel
                {
                    Id = result.Id,
                    Name = result.Name
                });

            var model = new GenreIndexModel()
            {
                Genres = listingResults
            };

            return View(model);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Genre genre = await _genres.GetById(id);

            if (genre != null)
            {
                ICollection<Movie> movies = await _genres.GetMovies(id);
                var detailModel = new GenreDetailModel
                {
                    Id = genre.Id,
                    Name = genre.Name,
                    Movies = movies
                        .Select(movie => new KeyValuePair<int, string>(movie.Id, movie.Title))
                        .ToDictionary(kvp => kvp.Key, kvp => kvp.Value)
                };

                return View(detailModel);
            }

            return NotFound();
        }
    }
}

KKRTheater/Development/KKRTheater/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KKRTheater.ViewModels;
using KKRTheater.ViewModels.Movies;
using TheaterData;
using TheaterData.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KKRTheater.Controllers
{
    public class MoviesController : Controller
    {
        private IMovie _movies;
        private IDirector _directors;
        private IActor _actors;
        private IGenre _genres;

        public MoviesController(IMovie movies, IDirector directors, IActor actors, IGenre genres)
        {
            _movies = movies;
            _directors = directors;
            _actors = actors;
            _genres = genres;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<Movie> movieModels = await _movies.GetAllLight();

            var listingResults = movieModels
                .Select(result => new MovieIndexListingModel
                {
                    Id = result.Id,
                    Rank = result.Rank,
                    Year = result.Year,
                    Title = result.Title,
                    Revenue = result.Revenue
                });

            var model = new MovieIndexModel()
            {
                Movies = listingResults
            };

            return View(model);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Movie movie = await _movies.GetById(id);
            if (movie != null)
            {
                ICollection<Actor> actors = await _movies.GetActors(movie.Id);
                ICollection<Genre> genres = await _movies.GetGenres(movie.Id);


                var detailModel = new MovieDetailModel
                {
                    Id = movie.Id,
                    Rank = movie.Rank,
                    Title = movie.Title,
                    Year = movie.Year,
                    Director = new DirectorListing() { Id = movie.Director.Id, Name = movie.Director.Name },
                    Runtime = movie.Runtime,
                    Revenue = movie.Revenue,
                    Metascore = movie.Metascore,
                    Description = movie.Description,
                    Actors = actors
                        .Select(actor => new KeyValuePair<int, string>(actor.Id, actor.Name))
                        .ToDictionary(kvp => kvp.Key, kvp => kvp.Value),
                    Genres = genres
                        .Select(genre => new KeyValuePair<int, string>(genre.Id, genre.Name))
                        .ToDictionary(kvp => kvp.Key, kvp => kvp.Value)
                };

                return View(detailModel);
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            await PopulateDirectorDropDownList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(MovieAddModel viewModel)
        {
            Director foundDirector = await _directors.GetById(viewModel.DirectorId);

            if (ModelState.IsValid)
            {
                Movie newMovie = new Movie
                {
                    Title = viewModel.Title,
                    Director = foundDirector,
                    Description = viewModel.Description,
                    Year = viewModel.Year,
                    Runtime = viewModel.Runtime,
                    Revenue = viewModel.Revenue
                };
                newMovie.Title = viewModel.Title;

                _movies.Add(newMovie);
                ModelState.Clear();
                return RedirectToAction($"Detail/{newMovie.Id}");
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, string actorSearchName = "")
        {
            //Avoid Null Exception when no search filter passed.
            if (string.IsNullOrEmpty(actorSearchName))
                actorSearchName = "";

            Movie foundMovie = await _movies.GetById(id);


            if (foundMovie != null)
            {
                MovieEditModel viewModel = new MovieEditModel
                {
                    Title = foundMovie.Title,
                    Id = foundMovie.Id,
                    Year = foundMovie.Year,
                    Revenue = foundMovie.Revenue,
                    Runtime = foundMovie.Runtime,
                    Description = foundMovie.Description,
                    Director = foundMovie.Director
                };

                //Build List of Actors
                ICollection<Actor> linkedActors = foundMovie.FilmCasts.Select(filmCast => filmCast.Actor).ToList();
                ICollection<Actor> allActors = await _actors.GetAllLight();

                List<AssignedEntity> assignedActors = allActors.OrderBy(actor => actor.Name).Where(actor => actor.Name.Contains(actorSearchName))
                    .Select(actor => new AssignedEntity
                    {
                        Id = actor.Id,
                        Name = actor.Name,
                        Assigned = linkedActors.Contains(actor)
                    }).ToList();


                viewModel.AssignedActors = assignedActors;


                //Build List of Genres  
                ICollection<Genre> linkedGenres = foundMovie.MovieGenres.Select(movieGenre => movieGenre.Genre).ToList();
                ICollection<Genre> allGenres = await _genres.GetAllLight();

                viewModel.AssignedGenres = allGenres
                    .Select(genre => new AssignedEntity
                    {
                        Id = genre.Id,
                        Name = genre.Name,
                        Assigned = linkedGenres.Contains(genre)
                    }).ToList();


                await PopulateDirectorDropDownList(foundMovie.Director.Id);
                return View(viewModel);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MovieEditModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Movie foundMovie = await _movies.GetById(viewModel.Id);

                if (foundMovie != null)
                {
                    Director foundDirector = await _directors.GetById(viewModel.DirectorId);

                    if (foundDirector != null)
                        foundMovie.Director = foundDirector;

                    if (!string.IsNullOrEmpty(viewModel.Title))
                        foundMovie.Title = viewModel.Title;
                    if (!string.IsNullOrEmpty(viewModel.Description))
                        foundMovie.Description = viewModel.Description;
                    if (viewModel.Year > 0)
                        foundMovie.Year = viewModel.Year;
                    if (viewModel.Runtime > 0)
                        foundMovie.Runtime = viewModel.Runtime;
                    if (viewModel.Revenue > 0)
                        foundMovie.Revenue = viewModel.Revenue;

                    foreach (AssignedEntity assignedActor in viewModel.AssignedActors)
                    {
                        if (assignedActor.Assigned)
                            _movies.AddActor(foundMovie, assignedActor.Id);

                        else if (foundMovie.FilmCasts.Select(filmCast => filmCast.ActorId).ToList().Contains(assignedActor.Id))
                            _movies.RemoveActor(foundMovie, assignedActor.Id);

                    }

                    foreach (AssignedEntity assignedGenre in viewModel.AssignedGenres)
                    {
                        if (assignedGenre.Assigned)
                            _movies.AddGenre(foundMovie, assignedGenre.Id);

                        else if (foundMovie.MovieGenres.Select(movieGenre => movieGenre.GenreId).ToList().Contains(assignedGenre.Id))
                            _movies.RemoveGenre(foundMovie, assignedGenre.Id);
                    }

                    _movies.Save();
                    ModelState.Clear();
                    return RedirectToAction($"Detail/{foundMovie.Id}");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Movie foundMovie = await _movies.GetById(id);
            if (foundMovie != null)
            {
                ICollection<Actor> actors = await _movies.GetActors(foundMovie.Id);
                ICollection<Genre> genres = await _movies.GetGenres(foundMovie.Id);

                MovieDeleteModel viewModel = new MovieDeleteModel()
                {

                    Id = foundMovie.Id,
                    Title = foundMovie.Title,
                    Year = foundMovie.Year,
                    DirectorName = foundMovie.Director.Name,
                    Runtime = foundMovie.Runtime,
                    Revenue = foundMovie.Revenue,
                    Description = foundMovie.Description,
                    Actors = actors
                    .Select(actor => actor.Name).ToList(),
                    Genres = genres
                    .Select(genre => genre.Name).ToList()
                };

                return View(viewModel);
            }

            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Movie foundMovie = await _movies.GetById(id);

            if (foundMovie != null)
            {
                _movies.Delete(foundMovie);
            }
            return RedirectToAction("Index");
        }

        private async Task PopulateDirectorDropDownList(object selectedDirector = null)
        {
            ICollection<Director> allDirectors = await _directors.GetAll();
            ViewBag.DirectorId = new SelectList(allDirectors, "Id", "Name", selectedDirector);

KKRTheater/Development/KKRTheater/Views/Movies/Add.cshtml
@model MovieAddModel

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}


<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">Add Movie</h2>
    </div>

    <div id="movieForm" class="panel panel-primary">
        <form action="Add" method="post" class="panel-body">
            <div class="form-group">
                <label asp-for="Title">Movie Title:</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year">Movie Release Year:</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <select asp-for="DirectorId" class="form-control" asp-items="ViewBag.DirectorId">
                    <option value="">-- Select Director --</option>
                </select>
                <span asp-validation-for="Director" class="text-danger" />
            </div>
            <div class="form-group">
                <label asp-for="Runtime">Movie Run Time (minutes):</label>
                <input asp-for="Runtime" class="form-control" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Revenue">Movie Revenue:</label>
                <input asp-for="Revenue" class="form-control" />
                <span asp-validation-for="Revenue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Movie Description:</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Add Movie</button>
            </div>
        </form>
    </div>
</div>

KKRTheater/Development/KKRTheater/Views/Movies/Delete.cshtml
@model MovieDeleteModel

<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">Delete @Model.Title</h2>
    </div>
</div>

<div class="row">Are you sure you want to delete?</div>

<div class="panel panel-danger">
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </form>
</div>

KKRTheater/Development/KKRTheater/Views/Movies/Detail.cshtml
@model MovieDetailModel

<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">@Model.Title</h2>
    </div>

    <div class="small-padding">
        <a asp-controller="Movies" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-lg">
            Edit
        </a> 
        <a asp-controller="Movies" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger btn-lg">
            Delete
        </a>
    </div>

    <div class="small-padding">
        <div class="panel panel-primary">
            <div class="panel-body">
                <h3>Info</h3>
                <div class="bg-info group-border">
                    <div class="mini-padding"><span class="panelHeader">Title:</span> @Model.Title</div>
                    <div class="mini-padding"><span class="panelHeader">Year Released:</span> @Model.Year</div>
                    <div class="mini-padding">
                        <span class="panelHeader">Director:</span>
                        <a asp-controller="Directors" asp-action="Detail" asp-route-id="@Model.Director.Id">
                            @Model.Director.Name
                        </a>
                    </div>
                    <div class="mini-padding"><span class="panelHeader">Runtime (minutes): </span> @Model.Runtime</div>
                    <div class="mini-padding"><span class="panelHeader">Revenue ($MM):</span> @Model.Revenue</div>
                    <div class="mini-padding"><span class="panelHeader">Description:</span> @Model.Description</div>
                </div>
                <div>
                    <h3>Actors</h3>
                    <ul class="list-group">
                        @foreach (KeyValuePair<int, string> actor in Model.Actors)
                        {
                            <li class="list-group-item">
                                <a asp-controller="Actors" asp-action="Detail" asp-route-id="@actor.Key">
                                    @actor.Value
                                </a>
                            </li>
                        }
                    </ul>
                </div>
                <div>
                    <h3>Genres</h3>
                    <ul class="list-group">
                        @foreach (KeyValuePair<int, string> genre in Model.Genres)
                        {
                            <li class="list-group-item">
                                <a asp-controller="Genres" asp-action="Detail" asp-route-id="@genre.Key">
                                    @genre.Value
                                </a>
                            </li>
                        }
                    </ul>
                </div>

            </div>
        </div>
    </div>
</div>

KKRTheater/Development/KKRTheater/Views/Movies/Edit.cshtml
@model MovieEditModel

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}


<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">Update @Model.Title</h2>
    </div>

    <div id="movieForm" class="panel panel-primary">
        <div>
            <div class="form-group">
                <label asp-for="Title">Movie Title:</label>
                <input asp-for="Title" class="form-control" form="movieForm" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year">Movie Release Year:</label>
                <input asp-for="Year" class="form-control" form="movieForm" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <select asp-for="DirectorId" class="form-control" asp-items="ViewBag.DirectorId" form="movieForm">
                    <option value="">-- Select Director --</option>
                </select>
                <span asp-validation-for="Director" class="text-danger" />
            </div>
            <div class="form-group">
                <label asp-for="Runtime">Movie Run Time (minutes):</label>
                <input asp-for="Runtime" class="form-control" form="movieForm" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Revenue">Movie Revenue:</label>
                <input asp-for="Revenue" class="form-control" form="movieForm" />
                <span asp-validation-for="Revenue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Movie Description:</label>
                <textarea asp-for="Description" class="form-control" form="movieForm"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <form asp-controller="Movies" asp-action="Edit" method="get">
            <p>
                Actor Name: <input type="text" name="actorSearchName">
                <input type="hidden" asp-for="@Model.Id" />
                <input type="submit" value="Filter" />
            </p>
        </form>

        <form asp-action="Edit" asp-controller="Actors" method="post" id="actorForm">
            <ul>

                @for (var i = 0; i < Model.AssignedActors.Count; i++)
                {
                    <li>
                        <input type="checkbox" asp-for="@Model.AssignedActors[i].Assigned" />
                        <label asp-for="@Model.AssignedActors[i].Assigned">@Model.AssignedActors[i].Name</label>
                        <input type="hidden" asp-for="@Model.AssignedActors[i].Id" />
                        <input type="hidden" asp-for="@Model.AssignedActors[i].Name" />
                    </li>
                }
            </ul>

            <ul>

                @for (var i = 0; i < Model.AssignedGenres.Count; i++)
                {
                    <li>
                        <input type="checkbox" asp-for="@Model.AssignedGenres[i].Assigned" />
                        <label asp-for="@Model.AssignedGenres[i].Assigned">@Model.AssignedGenres[i].Name</label>
                        <input type="hidden" asp-for="@Model.AssignedGenres[i].Id" />
                        <input type="hidden" asp-for="@Model.AssignedGenres[i].Name" />
                    </li>
                }
            </ul>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Update Actor</button>
            </div>
        </form>
    </div>

</div>

KKRTheater/Development/KKRTheater/Views/Movies/Index.cshtml
@model MovieIndexModel
<div class="container">
    <h3>Movie Catalog</h3>
    <div class="small-padding">
        <a asp-controller="Movies" asp-action="Add" class="btn btn-primary btn-lg">
            Add Movie
        </a>
    </div>
    <div class="small-padding">
        <table class="table-striped table-condensed table-hover table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Year</th>
                    <th scope="col">Revenue ($MM)</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                    @foreach (var movie in Model.Movies)
                    {

                        <tr class="">
                            <td class="row">@counter</td>
                            <td class="">@movie.Title</td>
                            <td class="">@movie.Year</td>
                            <td class="">@movie.Revenue</td>
                            <td class="">
                                <a asp-controller="Movies" asp-action="Detail" asp-route-id="@movie.Id">
                                    Details
                                </a> |
                                <a asp-controller="Movies" asp-action="Edit" asp-route-id="@movie.Id">
                                    Edit
                                </a> |
                                <a asp-controller="Movies" asp-action="Delete" asp-route-id="@movie.Id">
                                    Delete
                                </a>
                            </td>
                        </tr>
                        counter++;
                    }
                }
            </tbody>
        </table>
    </div>
</div>