KKRTheater/Development/KKRTheater/ViewModels/Directors/DirectorAddModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TheaterData.Entities;

namespace KKRTheater.ViewModels.Directors
{
    public class DirectorAddModel
    {        
        [MaxLength(255, ErrorMessage = "Too Long")]
        public string Name { get; set; }
        public DateTime Birthday { get; set; }
        public string Birthplace { get; set; }
        public string Bio { get; set; }
    }
}

KKRTheater/Development/KKRTheater/ViewModels/Directors/DirectorDeleteModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TheaterData.Entities;

namespace KKRTheater.ViewModels.Directors
{
    public class DirectorDeleteModel
    {        
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

KKRTheater/Development/KKRTheater/ViewModels/Directors/DirectorDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TheaterData.Entities;

namespace KKRTheater.ViewModels.Directors
{
    public class DirectorDetailModel
    {
        public int Id { get; set; }        
        public string Name { get; set; }
        public string Birthday { get; set; }
        public string Birthplace { get; set; }
        public string Bio { get; set; }
        public Dictionary<int,string> Movies { get; set; }
    }
}

KKRTheater/Development/KKRTheater/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KKRTheater.ViewModels;
using KKRTheater.ViewModels.Movies;
using TheaterData;
using TheaterData.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using KKRTheater.ViewModels.Directors;

namespace KKRTheater.Controllers
{
    public class DirectorsController : Controller
    {
        private IDirector _directors;
        private IMovie _movies;

        public DirectorsController(IDirector directors, IMovie movies)
        {
            _directors = directors;
            _movies = movies;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<Director> directors = await _directors.GetAll();

            var listingResults = directors
                .Select(director => new DirectorIndexListingModel
                {
                    Id = director.Id,
                    Name = director.Name
                });

            var model = new DirectorIndexModel()
            {
                Directors = listingResults
            };

            return View(model);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Director director = await _directors.GetById(id);

            if (director != null)
            {
                ICollection<Movie> movies = await _directors.GetMovies(id);
                var detailModel = new DirectorDetailModel
                {
                    Id = director.Id,
                    Name = director.Name,
                    Birthday = director.Birthday.Equals(DateTime.MinValue) ? "" : director.Birthday.ToString("MMMM dd yyyy"),
                    Birthplace = director.Birthplace,
                    Bio = director.Bio,
                    Movies = movies
                        .Select(movie => new KeyValuePair<int, string>(movie.Id, movie.Title))
                        .ToDictionary(kvp => kvp.Key, kvp => kvp.Value)
                };

                return View(detailModel);
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([Bind("Name")]Director director)
        {
            if (ModelState.IsValid)
            {
                Director foundDirector = await _directors.GetByName(director.Name);

                if (foundDirector == null)
                {
                    _directors.Add(director);
                    ModelState.Clear();
                    return RedirectToAction($"Detail/{director.Id}");
                }
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, string movieTitle = "")
        {
            //Avoid Null Exception when no search filter passed.
            if (movieTitle == null)
                movieTitle = "";


            Director foundDirector = await _directors.GetById(id);


            if (foundDirector != null)
            {
                DirectorEditModel viewModel = new DirectorEditModel();
                viewModel.Name = foundDirector.Name;
                viewModel.Id = foundDirector.Id;

                ICollection<Movie> linkedMovies = await _directors.GetMovies(foundDirector.Id);
                ICollection<Movie> allMovies = await _movies.GetAllLight();

                List<AssignedMovies> assignedMovies = allMovies.OrderBy(movie => movie.Title).Where(movie => movie.Title.Contains(movieTitle))
                    .Select(movie => new AssignedMovies
                    {
                        Id = movie.Id,
                        Title = movie.Title,
                        Assigned = linkedMovies.Contains(movie)
                    }).ToList();


                viewModel.AssignedMovies = assignedMovies;

                return View(viewModel);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DirectorEditModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Director foundDirector = await _directors.GetById(viewModel.Id);

                if (foundDirector != null)
                {
                    ICollection<Movie> linkedMovies = await _directors.GetMovies(foundDirector.Id);

                    foundDirector.Name = viewModel.Name;

                    foreach (AssignedMovies assignedMovie in viewModel.AssignedMovies)
                    {
                        if (assignedMovie.Assigned)
                            await _directors.AddMovie(foundDirector, assignedMovie.Id);

                        else if (linkedMovies.Select(movie => movie.Id).ToList().Contains(assignedMovie.Id))
                            await _directors.RemoveMovie(foundDirector, assignedMovie.Id);

                    }
                    _directors.Save();
                    ModelState.Clear();
                    return RedirectToAction($"Detail/{foundDirector.Id}");
                }
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Director foundDirector = await _directors.GetById(id);
            if (foundDirector != null)
            {
                DirectorDeleteModel viewModel = new DirectorDeleteModel();
                viewModel.Id = foundDirector.Id;
                viewModel.Name = foundDirector.Name;

                return View(viewModel);
            }


            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Director foundDirector = await _directors.GetById(id);

            if (foundDirector != null)
            {
                _directors.Delete(foundDirector);
            }
            return RedirectToAction("Index");
        }
    }
}

KKRTheater/Development/KKRTheater/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KKRTheater.ViewModels;
using KKRTheater.ViewModels.Movies;
using TheaterData;
using TheaterData.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KKRTheater.Controllers
{
    public class MoviesController : Controller
    {
        private IMovie _movies;
        private IDirector _directors;
        private IActor _actors;
        private IGenre _genres;

        public MoviesController(IMovie movies, IDirector directors, IActor actors, IGenre genres)
        {
            _movies = movies;
            _directors = directors;
            _actors = actors;
            _genres = genres;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<Movie> movieModels = await _movies.GetAllLight();

            var listingResults = movieModels
                .Select(result => new MovieIndexListingModel
                {
                    Id = result.Id,
                    Rank = result.Rank,
                    Year = result.Year,
                    Title = result.Title,
                    Revenue = result.Revenue
                });

            var model = new MovieIndexModel()
            {
                Movies = listingResults
            };

            return View(model);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Movie movie = await _movies.GetById(id);
            if (movie != null)
            {
                ICollection<Actor> actors = await _movies.GetActors(movie.Id);
                ICollection<Genre> genres = await _movies.GetGenres(movie.Id);


                var detailModel = new MovieDetailModel
                {
                    Id = movie.Id,
                    Rank = movie.Rank,
                    Title = movie.Title,
                    Year = movie.Year,
                    Director = new DirectorListing() { Id = movie.Director.Id, Name = movie.Director.Name },
                    Runtime = movie.Runtime,
                    Revenue = movie.Revenue,
                    Metascore = movie.Metascore,
                    Description = movie.Description,
                    Actors = actors
                        .Select(actor => new KeyValuePair<int, string>(actor.Id, actor.Name))
                        .ToDictionary(kvp => kvp.Key, kvp => kvp.Value),
                    Genres = genres
                        .Select(genre => new KeyValuePair<int, string>(genre.Id, genre.Name))
                        .ToDictionary(kvp => kvp.Key, kvp => kvp.Value)
                };

                return View(detailModel);
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            await PopulateDirectorDropDownList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(MovieAddModel viewModel)
        {
            Director foundDirector = await _directors.GetById(viewModel.DirectorId);

            if (ModelState.IsValid)
            {
                Movie newMovie = new Movie
                {
                    Title = viewModel.Title,
                    Director = foundDirector,
                    Description = viewModel.Description,
                    Year = viewModel.Year,
                    Runtime = viewModel.Runtime,
                    Revenue = viewModel.Revenue
                };
                newMovie.Title = viewModel.Title;

                _movies.Add(newMovie);
                ModelState.Clear();
                return RedirectToAction($"Detail/{newMovie.Id}");
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, string actorSearchName = "")
        {
            //Avoid Null Exception when no search filter passed.
            if (string.IsNullOrEmpty(actorSearchName))
                actorSearchName = "";

            Movie foundMovie = await _movies.GetById(id);


            if (foundMovie != null)
            {
                MovieEditModel viewModel = new MovieEditModel
                {
                    Title = foundMovie.Title,
                    Id = foundMovie.Id,
                    Year = foundMovie.Year,
                    Revenue = foundMovie.Revenue,
                    Runtime = foundMovie.Runtime,
                    Description = foundMovie.Description,
                    Director = foundMovie.Director
                };

                //Build List of Actors
                ICollection<Actor> linkedActors = foundMovie.FilmCasts.Select(filmCast => filmCast.Actor).ToList();
                ICollection<Actor> allActors = await _actors.GetAllLight();

                List<AssignedEntity> assignedActors = allActors.OrderBy(actor => actor.Name).Where(actor => actor.Name.Contains(actorSearchName))
                    .Select(actor => new AssignedEntity
                    {
                        Id = actor.Id,
                        Name = actor.Name,
                        Assigned = linkedActors.Contains(actor)
                    }).ToList();


                viewModel.AssignedActors = assignedActors;


                //Build List of Genres  
                ICollection<Genre> linkedGenres = foundMovie.MovieGenres.Select(movieGenre => movieGenre.Genre).ToList();
                ICollection<Genre> allGenres = await _genres.GetAllLight();

                viewModel.AssignedGenres = allGenres
                    .Select(genre => new AssignedEntity
                    {
                        Id = genre.Id,
                        Name = genre.Name,
                        Assigned = linkedGenres.Contains(genre)
                    }).ToList();


                await PopulateDirectorDropDownList(foundMovie.Director.Id);
                return View(viewModel);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MovieEditModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Movie foundMovie = await _movies.GetById(viewModel.Id);

                if (foundMovie != null)
                {
                    Director foundDirector = await _directors.GetById(viewModel.DirectorId);

                    if (foundDirector != null)
                        foundMovie.Director = foundDirector;

                    if (!string.IsNullOrEmpty(viewModel.Title))
                        foundMovie.Title = viewModel.Title;
                    if (!string.IsNullOrEmpty(viewModel.Description))
                        foundMovie.Description = viewModel.Description;
                    if (viewModel.Year > 0)
                        foundMovie.Year = viewModel.Year;
                    if (viewModel.Runtime > 0)
                        foundMovie.Runtime = viewModel.Runtime;
                    if (viewModel.Revenue > 0)
                        foundMovie.Revenue = viewModel.Revenue;

                    foreach (AssignedEntity assignedActor in viewModel.AssignedActors)
                    {
                        if (assignedActor.Assigned)
                            _movies.AddActor(foundMovie, assignedActor.Id);

                        else if (foundMovie.FilmCasts.Select(filmCast => filmCast.ActorId).ToList().Contains(assignedActor.Id))
                            _movies.RemoveActor(foundMovie, assignedActor.Id);

                    }

                    foreach (AssignedEntity assignedGenre in viewModel.AssignedGenres)
                    {
                        if (assignedGenre.Assigned)
                            _movies.AddGenre(foundMovie, assignedGenre.Id);

                        else if (foundMovie.MovieGenres.Select(movieGenre => movieGenre.GenreId).ToList().Contains(assignedGenre.Id))
                            _movies.RemoveGenre(foundMovie, assignedGenre.Id);
                    }

                    _movies.Save();
                    ModelState.Clear();
                    return RedirectToAction($"Detail/{foundMovie.Id}");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Movie foundMovie = await _movies.GetById(id);
            if (foundMovie != null)
            {
                ICollection<Actor> actors = await _movies.GetActors(foundMovie.Id);
                ICollection<Genre> genres = await _movies.GetGenres(foundMovie.Id);

                MovieDeleteModel viewModel = new MovieDeleteModel()
                {

                    Id = foundMovie.Id,
                    Title = foundMovie.Title,
                    Year = foundMovie.Year,
                    DirectorName = foundMovie.Director.Name,
                    Runtime = foundMovie.Runtime,
                    Revenue = foundMovie.Revenue,
                    Description = foundMovie.Description,
                    Actors = actors
                    .Select(actor => actor.Name).ToList(),
                    Genres = genres
                    .Select(genre => genre.Name).ToList()
                };

                return View(viewModel);
            }

            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Movie foundMovie = await _movies.GetById(id);

            if (foundMovie != null)
            {
                _movies.Delete(foundMovie);
            }
            return RedirectToAction("Index");
        }

        private async Task PopulateDirectorDropDownList(object selectedDirector = null)
        {
            ICollection<Director> allDirectors = await _directors.GetAll();
            ViewBag.DirectorId = new SelectList(allDirectors, "Id", "Name", selectedDirector);

KKRTheater/Development/KKRTheater/Views/Directors/Add.cshtml
@model DirectorAddModel

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}


<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">Add Actor</h2>
    </div>
</div>

<div id="actorForm" class="">
    <form action="Add" method="post">
        <div class="form-group">
            <label asp-for="Name">Director Name:</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Birthday">Birthday:</label>
            <input asp-for="Birthday" class="form-control" />
            <span asp-validation-for="Birthday" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Birthplace">Birthplace:</label>
            <input asp-for="Birthplace" class="form-control" />
            <span asp-validation-for="Birthplace" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Bio">Bio:</label>
            <textarea asp-for="Bio" class="form-control"></textarea>
            <span asp-validation-for="Bio" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Add Actor</button>
        </div>
    </form>
</div>

KKRTheater/Development/KKRTheater/Views/Directors/Delete.cshtml
@model DirectorDeleteModel

<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">Delete @Model.Name</h2>
    </div>
</div>

<div>Are you sure you want to delete?</div>

<div class="">
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KKRTheater/Development/KKRTheater/Views/Directors/Detail.cshtml
@model DirectorDetailModel

<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">@Model.Name</h2>
    </div>

    <div class="row">
        <a asp-controller="Directors" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-lg">
            Edit
        </a>
        <a asp-controller="Directors" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger btn-lg">
            Delete
        </a>
    </div>

    <div class="small-padding">
        <div class="panel panel-primary">
            <div class="panel-body">
                <h3>Info</h3>
                <div class="bg-info group-border">
                    <div class="mini-padding"><span class="panelHeader">Name:</span> @Model.Name</div>
                    <div class="mini-padding"><span class="panelHeader">Birthday:</span> @Model.Birthday</div>
                    <div class="mini-padding"><span class="panelHeader">Birthplace:</span> @Model.Birthplace</div>
                    <div class="mini-padding"><span class="panelHeader">Bio:</span> @Model.Bio</div>
                </div>
                <div>
                    <h3>Movies</h3>
                    <ul class="list-group">
                        @foreach (KeyValuePair<int, string> movie in Model.Movies)
                        {
                            <li class="list-group-item">
                                <a asp-controller="Movies" asp-action="Detail" asp-route-id="@movie.Key">
                                    @movie.Value
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>

KKRTheater/Development/KKRTheater/Views/Directors/Edit.cshtml
@model DirectorEditModel

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}


<div class="container">
    <div class="page-header clearfix">
        <h2 class="text-muted">Update @Model.Name</h2>
    </div>
</div>

<div id="movieForm" class="">
    <div class="form-group">
        <label asp-for="Name">Director Name:</label>
        <input asp-for="Name" class="form-control" value="@Model.Name" form="directorForm" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Birthday">Birthday:</label>
        <input asp-for="Birthday" type="date" class="form-control" form="directorForm"/>
        <span asp-validation-for="Birthday" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Birthplace">Birthplace:</label>
        <input asp-for="Birthplace" class="form-control" form="directorForm"/>
        <span asp-validation-for="Birthplace" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Bio">Bio:</label>
        <textarea asp-for="Bio" class="form-control" form="directorForm"></textarea>
        <span asp-validation-for="Bio" class="text-danger"></span>
    </div>
    <form asp-controller="Directors" asp-action="Edit" method="get">
        <p>
            Title: <input type="text" name="movieTitle">
            <input type="hidden" asp-for="@Model.Id" />
            <input type="submit" value="Filter" />
        </p>
    </form>
    <form asp-action="Edit" asp-controller="Directors" method="post" id="directorForm">
        <ul>

            @for (var i = 0; i < Model.AssignedMovies.Count; i++)
            {
                <li>
                    <input type="checkbox" asp-for="@Model.AssignedMovies[i].Assigned" />
                    <label asp-for="@Model.AssignedMovies[i].Assigned">@Model.AssignedMovies[i].Title</label>
                    <input type="hidden" asp-for="@Model.AssignedMovies[i].Id" />
                    <input type="hidden" asp-for="@Model.AssignedMovies[i].Title" />
                </li>
            }
        </ul>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Update Actor</button>
        </div>
    </form>
</div>

KKRTheater/Development/KKRTheater/Views/Directors/Index.cshtml
@model DirectorIndexModel
<div class="container-fluid">
    <h3>Director Catalog</h3>
    <div class="mt-2">
        <a asp-controller="Directors" asp-action="Add" class="btn btn-primary btn-lg">
            Add Director
        </a>
    </div>
    <div class="mt-2">
        <table class="table-striped table-condensed table-hover table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                    @foreach (var director in Model.Directors)
                    {

                        <tr class="">
                            <td class="row">@counter</td>
                            <td class="">@director.Name</td>
                            <td class="">
                                <a asp-controller="Directors" asp-action="Detail" asp-route-id="@director.Id">
                                    Details
                                </a>
                            </td>
                        </tr>

                        counter++;
                    }
                }
            </tbody>
        </table>
    </div>
</div>